import { useEffect, useMemo, useState } from 'react'
import { actualExpenses, actualIncome, availableMoney, budgetRows, forecast, goalMonths, recommendedSaving, rub, toKopecks } from './lib/finance'
import type { Account, Category, Goal, Obligation, Operation, OperationKind } from './lib/types'

type Tab = 'overview' | 'operations' | 'budget' | 'goals' | 'more'
type Modal = 'operation' | 'goal' | 'category' | 'account' | 'obligation' | null
type Store = { accounts:Account[]; categories:Category[]; goals:Goal[]; operations:Operation[]; obligations:Obligation[]; expectedIncome:number }
const empty:Store = { accounts:[], categories:[], goals:[], operations:[], obligations:[], expectedIncome:0 }
const key = 'financial-navigator-local-v2'
const labels:Record<Tab,string> = { overview:'Обзор', operations:'Операции', budget:'Бюджет', goals:'Цели', more:'Ещё' }
const marks:Record<Tab,string> = { overview:'⌂', operations:'☷', budget:'◔', goals:'◎', more:'•••' }

export default function App(){
 const [data,setData] = useState<Store>(()=>{ try{return JSON.parse(localStorage.getItem(key) || 'null') || empty}catch{return empty} })
 const [tab,setTab] = useState<Tab>('overview'), [modal,setModal] = useState<Modal>(null), [editingGoal,setEditingGoal] = useState<Goal|undefined>(), [toast,setToast] = useState('')
 const started = data.accounts.length>0
 useEffect(()=>localStorage.setItem(key,JSON.stringify(data)),[data])
 const available=availableMoney(data.accounts), income=actualIncome(data.operations), expenses=actualExpenses(data.operations), projected=forecast(data.accounts,data.operations,data.obligations), primary=data.goals.find(g=>g.primary)||data.goals[0]
 const message=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2500)}
 const openContext=()=>{ if(tab==='operations')setModal('operation'); else if(tab==='goals'){setEditingGoal(undefined);setModal('goal')} else if(tab==='budget')setModal('category'); else if(tab==='more')setModal('account'); else setModal('operation') }
 if(!started) return <Onboarding onFinish={setData}/>
 return <main className="app"><header className="top"><div><p className="eyebrow">{labels[tab]} · локальный режим</p><h1>{tab==='overview'?'Ваш план денег':labels[tab]}</h1></div><button className="profile" onClick={()=>{localStorage.removeItem(key);setData(empty)}} aria-label="Начать настройку заново">↻</button></header>
  {tab==='overview'&&<Overview available={available} projected={projected} income={income} expenses={expenses} goal={primary} obligations={data.obligations} onPay={(id:string)=>setData(d=>({...d,obligations:d.obligations.map(o=>o.id===id?{...o,paid:true}:o)}))}/>} 
  {tab==='operations'&&<Operations ops={data.operations} categories={data.categories} onConfirm={(id:string)=>setData(d=>({...d,operations:d.operations.map(o=>o.id===id?{...o,status:'actual'}:o)}))}/>} 
  {tab==='budget'&&<Budget categories={data.categories} ops={data.operations} expectedIncome={data.expectedIncome} onEditIncome={(n:number)=>setData(d=>({...d,expectedIncome:n}))}/>} 
  {tab==='goals'&&<Goals goals={data.goals} income={income} onAdd={()=>{setEditingGoal(undefined);setModal('goal')}} onEdit={(g:Goal)=>{setEditingGoal(g);setModal('goal')}} onTopUp={(id:string,n:number)=>setData(d=>({...d,goals:d.goals.map(g=>g.id===id?{...g,balanceKopecks:g.balanceKopecks+n}:g)}))}/>} 
  {tab==='more'&&<More accounts={data.accounts} obligations={data.obligations} onAdd={()=>setModal('account')} onAddObligation={()=>setModal('obligation')}/>} 
  <button className="fab" onClick={openContext} aria-label={`Добавить: ${labels[tab]}`}>+</button><nav aria-label="Основная навигация">{(Object.keys(labels) as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)} aria-current={tab===t?'page':undefined}><span>{marks[t]}</span>{labels[t]}</button>)}</nav>
  {modal==='operation'&&<OperationForm categories={data.categories} accounts={data.accounts} onClose={()=>setModal(null)} onSave={(o:Operation)=>{setData(d=>({...d,operations:[o,...d.operations]}));setModal(null);message('Операция добавлена')}}/>}
  {modal==='goal'&&<GoalForm goal={editingGoal} onClose={()=>setModal(null)} onSave={(g:Goal)=>{setData(d=>({...d,goals:editingGoal?d.goals.map(x=>x.id===g.id?g:x):[...d.goals.map(x=>({...x,primary:false})),g]}));setModal(null);message(editingGoal?'Цель изменена':'Цель добавлена')}}/>}
  {modal==='category'&&<CategoryForm onClose={()=>setModal(null)} onSave={(c:Category)=>{setData(d=>({...d,categories:[...d.categories,c]}));setModal(null);message('Категория добавлена')}}/>}
  {modal==='account'&&<AccountForm onClose={()=>setModal(null)} onSave={(a:Account)=>{setData(d=>({...d,accounts:[...d.accounts,a]}));setModal(null);message('Счёт добавлен')}}/>}
  {modal==='obligation'&&<ObligationForm onClose={()=>setModal(null)} onSave={(o:Obligation)=>{setData(d=>({...d,obligations:[...d.obligations,o]}));setModal(null);message('Обязательный платёж добавлен')}}/>}
  {toast&&<div className="toast" role="status">{toast}</div>}</main>
}

function Onboarding({onFinish}:{onFinish:(data:Store)=>void}){const [step,setStep]=useState(0),[name,setName]=useState('Основной счёт'),[balance,setBalance]=useState(''),[income,setIncome]=useState(''),[goal,setGoal]=useState(''),[target,setTarget]=useState('');const next=()=>setStep(s=>s+1);const done=()=>onFinish({accounts:[{id:crypto.randomUUID(),name:name||'Основной счёт',type:'card',balanceKopecks:toKopecks(balance||'0'),available:true}],categories:baseCategories(income),goals:goal?[{id:crypto.randomUUID(),name:goal,targetKopecks:toKopecks(target||'0'),balanceKopecks:0,monthlyKopecks:0,primary:true}]:[],operations:[],obligations:[],expectedIncome:toKopecks(income||'0')});return <main className="onboarding"><div className="onboard-card"><p className="eyebrow">Шаг {step+1} из 3</p>{step===0&&<><h1>Построим спокойный план</h1><p>Сначала укажем деньги, которыми можно пользоваться сейчас. Это не доход — только остаток на счёте или карте.</p><label>Название счёта<input value={name} onChange={e=>setName(e.target.value)} placeholder="Например, основная карта"/></label><label>Сколько на нём сейчас, ₽<input inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="Например, 25 000"/></label><button className="primary" onClick={next}>Дальше</button></>}{step===1&&<><h1>Когда и сколько приходит?</h1><p>Ожидаемый доход нужен, чтобы предложить рамку бюджета. Он не станет доступными деньгами до подтверждения.</p><label>Ожидаемый доход за месяц, ₽<input inputMode="decimal" value={income} onChange={e=>setIncome(e.target.value)} placeholder="Например, 90 000"/></label><button className="primary" onClick={next}>Собрать бюджет</button><button className="link-button" onClick={next}>Пока пропустить</button></>}{step===2&&<><h1>Есть важная цель?</h1><p>Цель можно добавить позже. Если укажете её сейчас, мы покажем прогресс и ориентир по сроку.</p><label>Название цели<input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Например, резерв"/></label><label>Нужная сумма, ₽<input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Например, 100 000"/></label><button className="primary" onClick={done}>Открыть мой план</button><button className="link-button" onClick={()=>{setGoal('');done()}}>Начать без цели</button></>}</div></main>}
function baseCategories(income:string):Category[]{const n=toKopecks(income||'0');return [['Жильё',25],['Продукты',18],['Транспорт',8],['Здоровье',6],['Прочее',8]].map(([name,p])=>({id:crypto.randomUUID(),name:name as string,limitKopecks:Math.round(n*(p as number)/100),suggestedPercent:p as number}))}
function Overview({available,projected,income,expenses,goal,obligations,onPay}:any){return <section><p className="explain">Доступно сейчас — деньги на счетах. Свободно до конца месяца — доступно минус запланированные обязательства плюс ожидаемые поступления.</p><div className="hero"><p>Свободно до конца месяца</p><strong>{rub(projected)}</strong><div className="hero-grid"><span>Доступно сейчас<b>{rub(available)}</b></span><span>Запланировано<b>{rub(obligations.filter((o:any)=>!o.paid).reduce((n:number,o:any)=>n+o.amountKopecks,0))}</b></span></div></div><section className="summary"><div><small>Доходы за месяц</small><b className="income">+{rub(income)}</b></div><div><small>Расходы за месяц</small><b>{rub(expenses)}</b></div></section>{goal?<section><h2>Главная цель</h2><article className="card goal"><div className="round">◎</div><div><h3>{goal.name}</h3><p>{rub(goal.balanceKopecks)} из {rub(goal.targetKopecks)}</p><Progress value={goal.balanceKopecks} max={goal.targetKopecks}/></div></article></section>:<Empty title="Добавьте цель" text="Так вы увидите, сколько уже отложено и чего не хватает."/>}<section><h2>Ближайшие обязательства</h2>{obligations.filter((o:any)=>!o.paid).length?<article className="card list">{obligations.filter((o:any)=>!o.paid).map((o:any)=><div key={o.id}><span className="round small">◷</span><span><b>{o.name}</b><small>К оплате {new Date(o.dueDate).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</small></span><button className="text-button" onClick={()=>onPay(o.id)}>Отметить оплату<br/>{rub(o.amountKopecks)}</button></div>)}</article>:<Empty title="Пока нет обязательств" text="Добавьте их в разделе «Ещё», чтобы они учитывались в прогнозе."/>}</section></section>}
function Operations({ops,categories,onConfirm}:any){const category=(id?:string)=>categories.find((c:any)=>c.id===id)?.name;return <section><p className="explain">Здесь фиксируются фактические траты и поступления. Нажмите «+», чтобы добавить операцию.</p><div className="summary"><div><small>Доходы</small><b className="income">+{rub(actualIncome(ops))}</b></div><div><small>Расходы</small><b>{rub(actualExpenses(ops))}</b></div></div>{ops.length?<article className="card list operations">{ops.map((o:any)=><div key={o.id}><span className="round small">{o.kind==='income'?'↓':'↑'}</span><span><b>{o.title}</b><small>{category(o.categoryId)||'Счёт'} · {o.status==='expected'?'Ожидается':'Факт'}</small></span><span className={o.kind==='income'?'income amount':'amount'}>{o.kind==='income'?'+':'−'}{rub(o.amountKopecks)}{o.status==='expected'&&<button className="mini" onClick={()=>onConfirm(o.id)}>Подтвердить</button>}</span></div>)}</article>:<Empty title="Ещё нет операций" text="Добавьте доход или расход — данные сразу появятся в бюджете и прогнозе."/>}</section>}
function Budget({categories,ops,expectedIncome,onEditIncome}:any){const [edit,setEdit]=useState(false),[input,setInput]=useState(String(expectedIncome/100));const rows=budgetRows(categories,ops),allocated=categories.reduce((n:number,c:any)=>n+c.limitKopecks,0);return <section><p className="explain">Это рамка месяца: лимиты можно менять, а расходы не блокируются. Они лишь показывают, сколько осталось в каждой категории.</p><div className="hero compact"><p>Ожидаемый доход месяца</p><strong>{rub(expectedIncome)}</strong><p>Распределено по категориям: {rub(allocated)}</p><Progress value={allocated} max={expectedIncome}/><button className="hero-button" onClick={()=>setEdit(!edit)}>Изменить доход</button>{edit&&<div className="inline-edit"><input value={input} inputMode="decimal" onChange={e=>setInput(e.target.value)}/><button onClick={()=>{onEditIncome(toKopecks(input));setEdit(false)}}>Сохранить</button></div>}</div><h2>Категории</h2>{rows.length?<article className="budget-list">{rows.map(({category,spent,remaining}:any)=><div key={category.id}><div><b>{category.name}</b><span>{rub(spent)} из {rub(category.limitKopecks)}</span></div><Progress value={spent} max={category.limitKopecks}/><small>{remaining>=0?`Осталось ${rub(remaining)}`:`Выше плана на ${rub(-remaining)}`}</small></div>)}</article>:<Empty title="Добавьте категории" text="Нажмите «+» — это позволит распределить ожидаемый доход."/>}</section>}
function Goals({goals,income,onAdd,onEdit,onTopUp}:any){return <section><p className="explain">Цели — отдельные конверты. Пополняйте их вручную; приложение покажет недостающую сумму и ориентир, если укажете ежемесячное пополнение.</p>{goals.length?goals.map((g:any)=><article className="card goal vertical" key={g.id}><div className="round">◎</div><div><h3>{g.name}</h3><p>{rub(g.balanceKopecks)} из {rub(g.targetKopecks)}</p><Progress value={g.balanceKopecks} max={g.targetKopecks}/><small>{goalMonths(g)?`Осталось примерно ${goalMonths(g)} мес.`:'Добавьте ежемесячное пополнение для ориентира по сроку'}</small><div className="actions"><button className="secondary" onClick={()=>onTopUp(g.id,100000)}>Пополнить на 1 000 ₽</button><button className="secondary" onClick={()=>onEdit(g)}>Изменить</button></div></div></article>):<Empty title="Первая цель" text="Нажмите «+», назовите цель и укажите сумму — так она станет частью вашего плана." action={onAdd}/>}<div className="saving-hint">Ориентир для накоплений от подтверждённого дохода: <b>{rub(recommendedSaving(income,10))}</b>. Вы сами решаете, переводить ли эту сумму.</div></section>}
function More({accounts,obligations,onAdd,onAddObligation}:any){return <section><p className="explain">Здесь лежат счета и обязательные платежи. Они отделены от ежедневных операций, чтобы прогноз был честным.</p><h2>Счета</h2>{accounts.map((a:any)=><article className="card details" key={a.id}><b>{a.name}</b><p>{a.available?'Доступные деньги':'Актив'} · {rub(a.balanceKopecks)}</p></article>)}<button className="secondary wide" onClick={onAdd}>Добавить счёт</button><h2>Обязательные платежи</h2>{obligations.length?<article className="card details">{obligations.map((o:any)=><p key={o.id}>{o.paid?'Оплачено':'Ожидается'} · {o.name} · {rub(o.amountKopecks)}</p>)}</article>:<Empty title="Нет обязательных платежей" text="Добавьте квартплату, интернет или кредит — они войдут в прогноз."/>}<button className="secondary wide" onClick={onAddObligation}>Добавить обязательный платёж</button></section>}
function Empty({title,text,action}:any){return <article className="empty"><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}>Добавить</button>}</article>}
function Progress({value,max}:{value:number;max:number}){return <div className="progress" role="progressbar" aria-valuenow={Math.min(value,max)} aria-valuemin={0} aria-valuemax={max}><i style={{width:`${Math.min(100,max?value/max*100:0)}%`}}/></div>}
function Sheet({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="sheet-backdrop"><div className="sheet"><div className="sheet-head"><h2>{title}</h2><button onClick={onClose} aria-label="Закрыть">×</button></div>{children}</div></div>}
function OperationForm({accounts,categories,onClose,onSave}:any){const [kind,setKind]=useState<OperationKind>('expense'),[amount,setAmount]=useState(''),[title,setTitle]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[category,setCategory]=useState(categories[0]?.id);return <Sheet title="Новая операция" onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!amount||!title)return;onSave({id:crypto.randomUUID(),kind,status:'actual',amountKopecks:toKopecks(amount),date,title,categoryId:kind==='expense'?category:undefined,accountId:accounts[0]?.id})}}><fieldset><legend>Тип</legend>{(['expense','income','transfer'] as OperationKind[]).map(k=><button type="button" className={kind===k?'chip selected':'chip'} onClick={()=>setKind(k)} key={k}>{k==='expense'?'Расход':k==='income'?'Доход':'Перевод'}</button>)}</fieldset><label>Сумма, ₽<input autoFocus required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label><label>Название<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Например, продукты"/></label><label>Дата<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{kind==='expense'&&<label>Категория<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<button className="primary">Сохранить</button></form></Sheet>}
function GoalForm({goal,onClose,onSave}:any){const [name,setName]=useState(goal?.name||''),[target,setTarget]=useState(goal?String(goal.targetKopecks/100):''),[balance,setBalance]=useState(goal?String(goal.balanceKopecks/100):''),[monthly,setMonthly]=useState(goal?.monthlyKopecks?String(goal.monthlyKopecks/100):'');return <Sheet title={goal?'Изменить цель':'Новая цель'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!name||!target)return;onSave({id:goal?.id||crypto.randomUUID(),name,targetKopecks:toKopecks(target),balanceKopecks:toKopecks(balance||'0'),monthlyKopecks:toKopecks(monthly||'0'),primary:true})}}><label>Название<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Например, резерв"/></label><label>Целевая сумма, ₽<input required inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Уже накоплено, ₽<input inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)}/></label><label>Плановое пополнение в месяц, ₽<input inputMode="decimal" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><button className="primary">Сохранить цель</button></form></Sheet>}
function CategoryForm({onClose,onSave}:any){const [name,setName]=useState(''),[limit,setLimit]=useState('');return <Sheet title="Новая категория" onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!name)return;onSave({id:crypto.randomUUID(),name,limitKopecks:toKopecks(limit||'0'),suggestedPercent:0})}}><label>Название<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Например, образование"/></label><label>Лимит на месяц, ₽<input inputMode="decimal" value={limit} onChange={e=>setLimit(e.target.value)}/></label><button className="primary">Добавить категорию</button></form></Sheet>}
function AccountForm({onClose,onSave}:any){const [name,setName]=useState(''),[balance,setBalance]=useState('');return <Sheet title="Новый счёт" onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!name)return;onSave({id:crypto.randomUUID(),name,type:'card',balanceKopecks:toKopecks(balance||'0'),available:true})}}><label>Название<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Например, наличные"/></label><label>Остаток, ₽<input inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)}/></label><button className="primary">Добавить счёт</button></form></Sheet>}
function ObligationForm({onClose,onSave}:any){const [name,setName]=useState(''),[amount,setAmount]=useState(''),[dueDate,setDueDate]=useState(new Date().toISOString().slice(0,10));return <Sheet title="Обязательный платёж" onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!name||!amount||!dueDate)return;onSave({id:crypto.randomUUID(),name,amountKopecks:toKopecks(amount),dueDate,paid:false,kind:'bill'})}}><p className="form-help">Платёж войдёт в прогноз, но не будет списан со счёта автоматически.</p><label>Что нужно оплатить<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Например, интернет"/></label><label>Сумма, ₽<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label><label>Дата оплаты<input required type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><button className="primary">Добавить в план</button></form></Sheet>}
