import { useEffect,useMemo,useState } from 'react'
import { actualExpenses,actualIncome,availableMoney,budgetRows,earlyRepayment,forecast,goalMonths,netPosition,recommendedSaving,rub } from './lib/finance'
import { demoAccounts,demoCategories,demoGoals,demoLoans,demoObligations,demoOperations } from './lib/demo'
import { ensureAnonymousSession,supabase } from './lib/supabase'
import type { Operation,OperationKind } from './lib/types'
type Tab='overview'|'operations'|'budget'|'goals'|'more'
const icons:Record<Tab,string>={overview:'⌂',operations:'☷',budget:'◔',goals:'◎',more:'•••'}
const labels:Record<Tab,string>={overview:'Обзор',operations:'Операции',budget:'Бюджет',goals:'Цели',more:'Ещё'}
export default function App(){
 const [tab,setTab]=useState<Tab>('overview'),[accounts]=useState(demoAccounts),[categories]=useState(demoCategories),[goals,setGoals]=useState(demoGoals),[ops,setOps]=useState(demoOperations),[obligations,setObligations]=useState(demoObligations),[showAdd,setShowAdd]=useState(false),[toast,setToast]=useState(''),[offline,setOffline]=useState(!navigator.onLine)
 useEffect(()=>{ensureAnonymousSession().catch(()=>setOffline(true));const online=()=>setOffline(false),off=()=>setOffline(true);addEventListener('online',online);addEventListener('offline',off);return()=>{removeEventListener('online',online);removeEventListener('offline',off)}} ,[])
 const available=availableMoney(accounts), income=actualIncome(ops), expenses=actualExpenses(ops), projected=forecast(accounts,ops,obligations), primary=goals.find(g=>g.primary)??goals[0]
 const saveOperation=(op:Operation)=>{setOps(a=>[op,...a]); setShowAdd(false); setToast('Операция сохранена');setTimeout(()=>setToast(''),3000);if(supabase)void supabase.from('operations').insert({id:op.id,kind:op.kind,status:op.status,amount_kopecks:op.amountKopecks,operation_date:op.date,title:op.title,account_id:op.accountId,category_id:op.categoryId})}
 return <main className="app"><header className="top"> <div><p className="eyebrow">{tab==='overview'?'Обзор':labels[tab]}</p><h1>{tab==='overview'?'Спокойно о деньгах':labels[tab]}</h1></div><button className="profile" aria-label="Настройки профиля">●</button></header>{offline&&<div className="notice">Нет сети — изменения сохранятся после подключения.</div>}
 {tab==='overview'&&<Overview available={available} projected={projected} income={income} expenses={expenses} goal={primary} obligations={obligations} onPay={id=>setObligations(a=>a.map(o=>o.id===id?{...o,paid:true}:o))}/>} 
 {tab==='operations'&&<Operations ops={ops} categories={categories} onConfirm={id=>setOps(a=>a.map(o=>o.id===id?{...o,status:'actual'}:o))}/>} 
 {tab==='budget'&&<Budget categories={categories} ops={ops} income={income}/>} 
 {tab==='goals'&&<Goals goals={goals} income={income} onTopUp={(id,amount)=>setGoals(a=>a.map(g=>g.id===id?{...g,balanceKopecks:g.balanceKopecks+amount}:g))}/>} 
 {tab==='more'&&<More net={netPosition(accounts,goals,demoLoans)} loans={demoLoans} obligations={obligations}/>} 
 <button className="fab" onClick={()=>setShowAdd(true)} aria-label="Добавить операцию">+</button><nav aria-label="Основная навигация">{(Object.keys(labels) as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)} aria-current={tab===t?'page':undefined}><span>{icons[t]}</span>{labels[t]}</button>)}</nav>{showAdd&&<OperationForm accounts={accounts} categories={categories} onClose={()=>setShowAdd(false)} onSave={saveOperation}/>} {toast&&<div className="toast" role="status">{toast}</div>}</main>
}
function Overview(p:{available:number;projected:number;income:number;expenses:number;goal:any;obligations:any[];onPay:(id:string)=>void}){return <section><div className="hero"><p>Свободно до конца месяца</p><strong>{rub(p.projected)}</strong><div className="spark"><i/><i/><i/><i/><i/></div><div className="hero-grid"><span>Доступно<b>{rub(p.available)}</b></span><span>Обязательства<b>{rub(p.obligations.filter(o=>!o.paid).reduce((n,o)=>n+o.amountKopecks,0))}</b></span></div></div><section className="summary"><div><small>Доходы за месяц</small><b className="income">+{rub(p.income)}</b></div><div><small>Расходы за месяц</small><b>{rub(p.expenses)}</b></div></section>{p.goal&&<section><h2>Цель месяца</h2><article className="card goal"><div className="round">◎</div><div><h3>{p.goal.name}</h3><p>{rub(p.goal.balanceKopecks)} из {rub(p.goal.targetKopecks)}</p><Progress value={p.goal.balanceKopecks} max={p.goal.targetKopecks}/></div></article></section>}<section><div className="section-title"><h2>Ближайшее</h2><span>Все</span></div><article className="card list">{p.obligations.filter(o=>!o.paid).map(o=><div key={o.id}><span className="round small">◷</span><span><b>{o.name}</b><small>К оплате {new Date(o.dueDate).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</small></span><button className="text-button" onClick={()=>p.onPay(o.id)}>Оплатить<br/>{rub(o.amountKopecks)}</button></div>)}</article></section></section>}
function Operations({ops,categories,onConfirm}:{ops:Operation[];categories:any[];onConfirm:(id:string)=>void}){const category=(id?:string)=>categories.find(c=>c.id===id)?.name;return <section><div className="month">Июль 2026 <button aria-label="Выбрать месяц">⌄</button></div><div className="summary"><div><small>Доходы</small><b className="income">+{rub(actualIncome(ops))}</b></div><div><small>Расходы</small><b>{rub(actualExpenses(ops))}</b></div></div><h2>Операции</h2><article className="card list operations">{ops.map(o=><div key={o.id}><span className="round small">{o.kind==='income'?'↓':o.kind==='expense'?'↑':'↔'}</span><span><b>{o.title}</b><small>{category(o.categoryId)||'Основной счёт'} · {o.status==='expected'?'Ожидается':o.status==='planned'?'План':'Факт'}</small></span><span className={o.kind==='income'?'income amount':'amount'}>{o.kind==='income'?'+':'−'}{rub(o.amountKopecks)}{o.status==='expected'&&<button className="mini" onClick={()=>onConfirm(o.id)}>Подтвердить</button>}</span></div>)}</article></section>}
function Budget({categories,ops,income}:{categories:any[];ops:Operation[];income:number}){const rows=budgetRows(categories,ops);const allocated=categories.reduce((n,c)=>n+c.limitKopecks,0);return <section><div className="month">План на июль 2026</div><div className="hero compact"><p>Ожидаемый доход</p><strong>{rub(Math.max(income,12650000))}</strong><p>Распределено {rub(allocated)}</p><Progress value={allocated} max={Math.max(income,12650000)}/></div><h2>Категории</h2><article className="budget-list">{rows.map(({category,spent,remaining})=><div key={category.id}><div><b>{category.name}</b><span>{rub(spent)} из {rub(category.limitKopecks)}</span></div><Progress value={spent} max={category.limitKopecks}/><small>{remaining>=0?`Осталось ${rub(remaining)}`:`Выше плана на ${rub(-remaining)}`}</small></div>)}</article></section>}
function Goals({goals,income,onTopUp}:{goals:any[];income:number;onTopUp:(id:string,n:number)=>void}){return <section><div className="hero compact"><p>Рекомендуем направить в накопления</p><strong>{rub(recommendedSaving(income||9500000,goals[0]?.basePercent??10))}</strong><p>Это расчёт на основе подтверждённого дохода</p></div><h2>Конверты и цели</h2>{goals.map(g=><article className="card goal vertical" key={g.id}><div className="round">◎</div><div><h3>{g.name}</h3><p>{rub(g.balanceKopecks)} из {rub(g.targetKopecks)}</p><Progress value={g.balanceKopecks} max={g.targetKopecks}/><small>{goalMonths(g) ? `Ориентир: ещё ${goalMonths(g)} мес.` : 'Добавьте регулярное пополнение для прогноза'}</small><button className="secondary" onClick={()=>onTopUp(g.id,100000)}>Пополнить на 1 000 ₽</button></div></article>)}</section>}
function More({net,loans,obligations}:{net:number;loans:any[];obligations:any[]}){const [extra,setExtra]=useState(1000000);const scenario=earlyRepayment(loans[0],extra);return <section><div className="summary single"><small>Чистое финансовое положение</small><b>{rub(net)}</b></div><h2>Обязательства и планы</h2><article className="card details"><h3>{loans[0].name}</h3><p>Остаток {rub(loans[0].balanceKopecks)} · {loans[0].annualRatePercent}% годовых</p><p>Платёж {rub(loans[0].paymentKopecks)} в месяц</p><label>Дополнительный платёж<input type="number" value={extra/100} min="0" step="1000" onChange={e=>setExtra(Number(e.target.value)*100)}/></label><div className="calculation">Расчётный сценарий: {scenario.months?`около ${scenario.months} мес., проценты ${rub(scenario.interestKopecks!)}`:'недостаточно данных для расчёта'}. Это не финансовая рекомендация.</div></article><article className="card details"><h3>Внутренние напоминания</h3>{obligations.map(o=><p key={o.id}>{o.paid?'Оплачено':'Ожидается'} · {o.name} · {rub(o.amountKopecks)}</p>)}</article></section>}
function Progress({value,max}:{value:number;max:number}){return <div className="progress" role="progressbar" aria-valuenow={Math.min(value,max)} aria-valuemin={0} aria-valuemax={max}><i style={{width:`${Math.min(100,max?value/max*100:0)}%`}}/></div>}
function OperationForm({accounts,categories,onClose,onSave}:{accounts:any[];categories:any[];onClose:()=>void;onSave:(o:Operation)=>void}){const [kind,setKind]=useState<OperationKind>('expense'),[amount,setAmount]=useState(''),[title,setTitle]=useState(''),[category,setCategory]=useState(categories[0]?.id);const submit=(e:React.FormEvent)=>{e.preventDefault();const amountKopecks=Math.round(Number(amount.replace(',','.'))*100);if(!amountKopecks||!title)return;onSave({id:crypto.randomUUID(),kind,status:'actual',amountKopecks,date:new Date().toISOString().slice(0,10),title,categoryId:kind==='expense'?category:undefined,accountId:accounts[0]?.id})};return <div className="sheet-backdrop" role="presentation"><form className="sheet" onSubmit={submit}><div className="sheet-head"><h2>Новая операция</h2><button type="button" onClick={onClose} aria-label="Закрыть">×</button></div><fieldset><legend>Тип</legend>{(['expense','income','transfer'] as OperationKind[]).map(k=><button type="button" className={kind===k?'chip selected':'chip'} onClick={()=>setKind(k)} key={k}>{k==='expense'?'Расход':k==='income'?'Доход':'Перевод'}</button>)}</fieldset><label>Сумма, ₽<input autoFocus inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required placeholder="0"/></label><label>Название<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder={kind==='expense'?'Например, продукты':'Например, зарплата'}/></label>{kind==='expense'&&<label>Категория<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<button className="primary" type="submit">Сохранить</button></form></div>}
